# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengboshiBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6708\u4efd')),
                ('date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6545\u969c\u65e5\u671f')),
                ('manufacturer', models.CharField(choices=[('1', 'HP'), ('2', 'IBM'), ('3', 'Dell'), ('4', 'EMC'), ('5', '\u6d6a\u6f6e'), ('6', '\u8054\u60f3'), ('7', '\u534e\u4e3a'), ('8', 'DELL\u5200\u7bb1')], max_length=2, verbose_name='\u5382\u5546')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u578b\u53f7')),
                ('id_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('description', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u6545\u969c\u8bf4\u660e')),
                ('spare_part_info', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u5907\u4ef6\u5177\u4f53\u4fe1\u606f')),
                ('solution_state', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u89e3\u51b3\u72b6\u6001')),
                ('idc', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u673a\u623f')),
                ('cabinet', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u673a\u67dc')),
                ('u_slot', models.CharField(blank=True, max_length=10, null=True, verbose_name='U\u4f4d')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('finish_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6545\u969c\u89e3\u51b3\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u9e4f\u535a\u58eb\u6545\u969c\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='PengboshiReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6708\u4efd')),
                ('date', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u65e5\u671f')),
                ('duty_operator', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u503c\u73ed\u4eba\u5458')),
                ('check_times', models.IntegerField(blank=True, null=True, verbose_name='\u5de1\u68c0\u6b21\u6570')),
                ('entrust_work', models.CharField(blank=True, max_length=160, null=True, verbose_name='\u5ba2\u6237\u59d4\u6258\u4f5c\u4e1a')),
                ('SN', models.CharField(blank=True, max_length=160, null=True, verbose_name='SN')),
                ('person_in_out', models.IntegerField(blank=True, null=True, verbose_name='\u4eba\u5458\u8fdb\u51fa')),
                ('device_in_out', models.IntegerField(blank=True, null=True, verbose_name='\u8bbe\u5907\u8fdb\u51fa')),
                ('breakdown_out_in', models.IntegerField(blank=True, null=True, verbose_name='\u6545\u969c\u7533\u62a5')),
                ('entrust_times', models.IntegerField(blank=True, null=True, verbose_name='\u59d4\u6258\u4f5c\u4e1a\u6b21\u6570')),
            ],
            options={
                'verbose_name_plural': '\u9e4f\u535a\u58eb\u6bcf\u65e5\u8fd0\u7ef4\u62a5\u544a',
            },
        ),
    ]
